#version: '3.8'
#services:
#  mongo:
#    image: mongo:latest
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_DATABASE: feeddb
#    restart: always

version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: feeddb
    restart: always

  feed-search-app:
    image: feed-search-app
    build: .  # Or the correct path to your Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/feeddb
    restart: always
